"""Optional integration tests: Python 3 + Playwright + Chromium with WebGL 2.
Run: python tests/browser.e2e.py
The split source is assembled in memory for an offline browser test; the actual
server routes are tested separately by `npm test`. No network dependency.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,os,shutil,time
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'.test-output';OUT.mkdir(exist_ok=True)
SCRIPTS=['math','materials','fuel-world','shaders','renderer','fuel-renderer','audio','app']
def document():
 text=(ROOT/'index.html').read_text()
 text=text.replace('<link rel="stylesheet" href="styles.css">','<style>'+(ROOT/'styles.css').read_text()+'</style>')
 for name in SCRIPTS:
  script=(ROOT/f'src/{name}.js').read_text()
  if name=='app':script=script.replace("capture=params.has('capture')","capture=true")
  text=text.replace(f'<script defer src="src/{name}.js"></script>','').replace('</body>',f'<script>{script}</script></body>')
 return text
report={'browser':'Chromium / WebGL 2 / SwiftShader','tests':[],'errors':[],'notes':['Local HTTP navigation is blocked by container browser policy; split source is assembled offline for GUI tests. Node tests verify the server routes.','Touch is emulated; physical iPhone / Safari was not tested.']}
def save():
 text=json.dumps(report,ensure_ascii=False,indent=2)
 (OUT/'browser-report.json').write_text(text)
 (ROOT/'tests/browser-report.json').write_text(text)
def check(name,result):
 report['tests'].append({'name':name,'pass':bool(result)});save();print(('PASS ' if result else 'FAIL ')+name,flush=True)
 if not result:raise AssertionError(name)
def load(page):
 page.on('pageerror',lambda e:report['errors'].append(str(e)))
 page.on('console',lambda m:report['errors'].append(m.text) if m.type=='error' else None)
 page.set_content(document(),wait_until='load',timeout=30000)
 page.wait_for_function('!!window.__IGNIS__ || !document.getElementById("error").hidden',timeout=90000)
 check('WebGL initializes without error overlay',page.evaluate('!!window.__IGNIS__ && document.getElementById("error").hidden'))
 page.evaluate('document.getElementById("loading").hidden=true')
def step(page,dt=.03):page.evaluate('(dt)=>__IGNIS__.renderStep(dt)',dt)
def advance(page,seconds):page.evaluate('(t)=>{for(let i=0;i<Math.round(t*60);i++)__IGNIS__.world.update(1/60,__IGNIS__.state);}',seconds)
with sync_playwright() as p:
 args=['--no-sandbox','--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']
 browser=p.chromium.launch(executable_path=os.environ.get('IGNIS_CHROMIUM') or shutil.which('chromium') or p.chromium.executable_path,headless=True,args=args)
 page=browser.new_page(viewport={'width':1280,'height':800},device_scale_factor=1)
 load(page)
 check('Four selectable materials and a throw action',page.locator('.material-card').count()==4 and page.is_enabled('#quick-throw'))
 check('Standard quality, sound off, feed mode by default',page.evaluate('__IGNIS__.state.quality==="medium" && !__IGNIS__.audio.enabled && __IGNIS__.state.mode==="feed"'))
 page.screenshot(path=str(OUT/'desktop.png'),timeout=60000)
 # Keep the same quality/field, but reduce test-only output raster size.
 page.evaluate('__IGNIS__.renderer.config={...__IGNIS__.renderer.config,scale:.42,maxPixels:240000}')
 card=page.locator('[data-material="paper"]').bounding_box()
 page.mouse.move(card['x']+35,card['y']+35);page.mouse.down();page.mouse.move(750,395,steps=5)
 check('Dragging lifts the actual 3D paper',page.evaluate('!!__IGNIS__.world.held && __IGNIS__.world.held.kind==="paper"'))
 page.mouse.move(870,450,steps=3);page.mouse.up()
 check('Release launches one solid body and clears held state',page.evaluate('__IGNIS__.world.bodies.length===1 && !__IGNIS__.world.held && __IGNIS__.world.bodies[0].stage==="flight"'))
 step(page,.03)
 check('New throw produces no premature combustion source',page.evaluate('__IGNIS__.world.sourceCount===0'))
 advance(page,7);step(page)
 check('Paper lands, chars and contributes a local fire source',page.evaluate('__IGNIS__.world.bodies[0].stage==="burning" && __IGNIS__.world.bodies[0].progress>0 && __IGNIS__.world.sourceCount===1 && __IGNIS__.world.boost>0'))
 check('Simulation receives the new GPU source uniform',page.evaluate('(()=>{const p=__IGNIS__.renderer.programs.simulation;return p.gl.getUniform(p.id,p.uniforms.get("uFeedCount").location)===1})()'))
 page.screenshot(path=str(OUT/'paper-burning.png'),timeout=60000)
 page.click('[data-material="wood"]')
 check('Selecting a card does not immediately throw',page.evaluate('__IGNIS__.selectedMaterial==="wood" && __IGNIS__.world.bodies.length===1'))
 page.click('#quick-throw')
 check('Throw button uses the selected material',page.evaluate('__IGNIS__.world.bodies.at(-1).kind==="wood"'))
 advance(page,10);step(page)
 check('Material-specific burn rates differ',page.evaluate('__IGNIS__.world.bodies.find(b=>b.kind==="wood").progress<__IGNIS__.world.bodies.find(b=>b.kind==="paper").progress'))
 page.click('#pause');before=page.evaluate('JSON.stringify({time:__IGNIS__.state.time,world:__IGNIS__.world.info()})');step(page,.05)
 check('Pause freezes both flame time and all fuel bodies',page.evaluate('JSON.stringify({time:__IGNIS__.state.time,world:__IGNIS__.world.info()})')==before)
 page.click('#pause');page.click('#orbit-mode');yaw=page.evaluate('__IGNIS__.cameraGoal.yaw')
 page.mouse.move(1020,400);page.mouse.down();page.mouse.move(1110,410,steps=4);page.mouse.up()
 check('Orbit remains available and keeps the original direction',page.evaluate('__IGNIS__.cameraGoal.yaw')<yaw)
 page.click('#wind-mode');page.mouse.move(845,370);page.mouse.down();page.mouse.move(985,375,steps=4);page.mouse.up()
 check('Wind interaction remains available',page.evaluate('Math.hypot(...__IGNIS__.state.touch.slice(2))>.1'))
 page.click('#settings-toggle');check('Settings opens',page.is_visible('#settings'))
 for quality in ['low','high','ultra','medium']:
  page.select_option('#quality',quality);check('Quality '+quality+' preserves the added objects',page.evaluate('__IGNIS__.world.bodies.length===2'))
  page.evaluate('__IGNIS__.renderer.config={...__IGNIS__.renderer.config,scale:.3,maxPixels:100000}')
  step(page,0)
 check('Quality changes produce no WebGL errors',page.evaluate('__IGNIS__.renderer.gl.getError()===0'))
 page.click('#clear-fuel');step(page,0)
 check('Clear removes added bodies and local sources',page.evaluate('__IGNIS__.world.bodies.length===0 && __IGNIS__.world.sourceCount===0 && __IGNIS__.world.boost===0'))
 page.click('#close-settings');page.click('#sound');page.wait_for_timeout(100)
 check('Sound starts only after its button is pressed',page.evaluate('__IGNIS__.audio.enabled && __IGNIS__.audio.context.state==="running"'))
 page.click('#quick-throw');advance(page,3);step(page)
 check('Material sound events leave audio running',page.evaluate('__IGNIS__.audio.context.state==="running"'))
 page.click('#sound');check('Sound stops scheduling after toggle off',page.evaluate('!__IGNIS__.audio.enabled && __IGNIS__.audio.timer===null'))
 page.click('#immersive');check('Immersive mode disables hidden UI focus targets',page.evaluate('document.body.classList.contains("immersive") && [...document.querySelectorAll(".ui")].every(x=>x.inert)'))
 page.keyboard.press('Escape');check('Escape restores UI',page.evaluate('!document.body.classList.contains("immersive")'))
 page.keyboard.press('2');check('Number shortcuts select material',page.evaluate('__IGNIS__.selectedMaterial==="cardboard"'))
 count=page.evaluate('__IGNIS__.world.bodies.length');page.wait_for_timeout(160);page.keyboard.press('f');check('F throws the selected material',page.evaluate('__IGNIS__.world.bodies.length')==count+1)
 # Actual requestAnimationFrame loop, not only explicit stepping.
 page.evaluate('__IGNIS__.resume()');page.wait_for_timeout(120);page.evaluate('__IGNIS__.freeze()')
 check('Animation loop advances after resuming',page.evaluate('__IGNIS__.renderer.frame>10'))
 page.close()
 context=browser.new_context(viewport={'width':390,'height':844},device_scale_factor=1,is_mobile=True,has_touch=True)
 mobile=context.new_page();load(mobile)
 check('Mobile also defaults to standard quality',mobile.evaluate('__IGNIS__.state.quality==="medium"'))
 check('No mobile horizontal overflow',mobile.evaluate('document.documentElement.scrollWidth<=390'))
 mobile.screenshot(path=str(OUT/'mobile.png'),timeout=60000)
 cdp=context.new_cdp_session(mobile)
 def touch(kind,points):cdp.send('Input.dispatchTouchEvent',{'type':kind,'touchPoints':points})
 card=mobile.locator('[data-material="twig"]').bounding_box();x=card['x']+35;y=card['y']+30
 touch('touchStart',[{'x':x,'y':y,'id':1}]);touch('touchMove',[{'x':205,'y':335,'id':1}]);touch('touchEnd',[])
 check('One-finger material drag throws on mobile',mobile.evaluate('__IGNIS__.world.bodies.length===1 && __IGNIS__.world.bodies[0].kind==="twig"'))
 count=mobile.evaluate('__IGNIS__.world.bodies.length')
 touch('touchStart',[{'x':190,'y':380,'id':1}]);touch('touchCancel',[])
 check('Touch cancellation does not accidentally throw',mobile.evaluate('__IGNIS__.world.bodies.length')==count and mobile.evaluate('!__IGNIS__.world.held'))
 dist=mobile.evaluate('__IGNIS__.cameraGoal.distance')
 touch('touchStart',[{'x':125,'y':365,'id':1},{'x':265,'y':365,'id':2}]);touch('touchMove',[{'x':100,'y':365,'id':1},{'x':290,'y':365,'id':2}]);touch('touchEnd',[])
 check('Pinch zoom cancels the held item without throwing it',mobile.evaluate('__IGNIS__.cameraGoal.distance')<dist and mobile.evaluate('__IGNIS__.world.bodies.length')==count)
 mobile.click('#orbit-mode');yaw=mobile.evaluate('__IGNIS__.cameraGoal.yaw')
 touch('touchStart',[{'x':130,'y':330,'id':1}]);touch('touchMove',[{'x':245,'y':330,'id':1}]);touch('touchEnd',[])
 check('One-finger orbit direction is unchanged on mobile',mobile.evaluate('__IGNIS__.cameraGoal.yaw')<yaw)
 mobile.click('#settings-toggle');r=mobile.locator('#settings').bounding_box()
 check('Mobile settings stays within the visible screen',r['x']>=0 and r['x']+r['width']<=390 and r['y']>=0 and r['y']+r['height']<=844)
 mobile.click('#close-settings')
 mobile.set_viewport_size({'width':390,'height':700});mobile.evaluate('__IGNIS__.resetCamera();__IGNIS__.renderStep(1)')
 mobile.screenshot(path=str(OUT/'mobile-short.png'),timeout=60000)
 check('Short mobile layout has no overflow',mobile.evaluate('document.documentElement.scrollWidth<=390'))
 mobile.set_viewport_size({'width':844,'height':390});mobile.evaluate('__IGNIS__.resetCamera();__IGNIS__.renderStep(1)')
 mobile.screenshot(path=str(OUT/'landscape.png'),timeout=60000)
 check('Landscape layout fits the viewport',mobile.evaluate('document.documentElement.scrollWidth<=844'))
 mobile.close();context.close()
 # Reduced motion startup and all shader compilation failures are handled.
 reduced=browser.new_page(viewport={'width':600,'height':700},reduced_motion='reduce');load(reduced)
 check('Reduced-motion preference starts paused',reduced.evaluate('__IGNIS__.state.paused'))
 reduced.close();check('No runtime / shader / console errors during integration tests',len(report['errors'])==0)
 browser.close();save()
 print('ALL BROWSER TESTS PASSED',flush=True)
