# Optional: Python 3 + Playwright + a Chromium installation.
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,time,hashlib,os,shutil
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'.test-output'
OUT.mkdir(exist_ok=True)

def document(capture=True):
    text=(ROOT/'index.html').read_text()
    text=text.replace('<link rel="stylesheet" href="styles.css">','<style>'+(ROOT/'styles.css').read_text()+'</style>')
    for name in ['math','shaders','renderer','audio','app']:
        script=(ROOT/f'src/{name}.js').read_text()
        if capture and name=='app': script=script.replace("capture=params.has('capture')","capture=true")
        text=text.replace(f'<script defer src="src/{name}.js"></script>','')
        text=text.replace('</body>',f'<script>{script}</script></body>')
    return text

report={'browser':'Chromium / ANGLE SwiftShader / WebGL 2','tests':[], 'errors':[]}
def check(name,result):
    report['tests'].append({'name':name,'pass':bool(result)})
    print(('PASS ' if result else 'FAIL ')+name,flush=True)
    (OUT/'browser-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
    if not result: raise AssertionError(name)

def load(page, capture=True):
    page.on('pageerror',lambda e:report['errors'].append(str(e)))
    page.on('console',lambda m: report['errors'].append(m.text) if m.type=='error' else None)
    page.set_content(document(capture),wait_until='load',timeout=20000)
    page.wait_for_function('!!window.__IGNIS__ || !document.getElementById("error").hidden',timeout=60000)
    check('Renderer initializes',page.evaluate('!!window.__IGNIS__'))
    page.evaluate('document.getElementById("loading").hidden=true')

def step(page,dt=1/30):
    page.evaluate('(dt)=>window.__IGNIS__.renderStep(dt)',dt)

with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('IGNIS_CHROMIUM') or shutil.which('chromium') or shutil.which('chrome') or p.chromium.executable_path,headless=True,args=['--no-sandbox','--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage'])
    page=browser.new_page(viewport={'width':1280,'height':800},device_scale_factor=1)
    load(page)
    check('Japanese title and controls',page.title().startswith('IGNIS') and page.get_by_role('button',name='一時停止',exact=True).count()==1)
    check('HDR framebuffer and shader status',page.evaluate('window.__IGNIS__.renderer.gl.getError()===0'))
    check('Default standard quality',page.evaluate('window.__IGNIS__.state.quality==="medium"'))
    page.screenshot(path=str(OUT/'desktop.png'),timeout=60000)
    before=page.evaluate('window.__IGNIS__.state.time')
    step(page,.033)
    check('Animation time advances',page.evaluate('window.__IGNIS__.state.time')>before)
    page.click('#pause')
    before=page.evaluate('window.__IGNIS__.state.time')
    step(page,.04)
    check('Pause freezes simulation time',page.evaluate('window.__IGNIS__.state.time')==before)
    check('Pause accessible state',page.get_attribute('#pause','aria-pressed')=='true')
    page.click('#pause')
    yaw=page.evaluate('window.__IGNIS__.cameraGoal.yaw')
    page.mouse.move(920,470);page.mouse.down();page.mouse.move(1020,490,steps=5);page.mouse.up()
    check('Orbit drag direction',page.evaluate('window.__IGNIS__.cameraGoal.yaw')<yaw)
    step(page)
    page.mouse.move(1050,400);page.mouse.down();page.mouse.move(1050,1);page.mouse.up()
    check('Camera never goes below floor',page.evaluate('window.__IGNIS__.cameraGoal.pitch>=.035'))
    page.mouse.wheel(0,-100000)
    page.wait_for_timeout(60)
    check('Zoom is bounded',page.evaluate('window.__IGNIS__.cameraGoal.distance>=2.9'))
    page.click('#wind-mode')
    page.mouse.move(860,380);page.mouse.down();page.mouse.move(1010,370,steps=8);page.mouse.up()
    check('Pointer injects a local wind impulse',page.evaluate('Math.hypot(...window.__IGNIS__.state.touch.slice(2))>.1'))
    page.click('#settings-toggle')
    check('Settings opens with accessible state',page.is_visible('#settings') and page.get_attribute('#settings-toggle','aria-expanded')=='true')
    page.locator('#fuel').evaluate("el=>{el.value='1.4';el.dispatchEvent(new Event('input',{bubbles:true}));}")
    check('Fuel slider updates state and label',page.evaluate('window.__IGNIS__.state.fuel===1.4') and page.inner_text('#fuel-value')=='力強く')
    page.locator('#wind').evaluate("el=>{el.value='0.65';el.dispatchEvent(new Event('input',{bubbles:true}));}")
    check('Wind slider updates state',page.evaluate('window.__IGNIS__.state.wind===.65'))
    page.set_viewport_size({'width':640,'height':520})
    for quality in ['low','high','ultra','medium']:
        page.select_option('#quality',quality)
        step(page,0)
        check('Quality '+quality+' resamples without GL errors',page.evaluate('(q)=>window.__IGNIS__.renderer.quality===q && !window.__IGNIS__.renderer.initialize && window.__IGNIS__.renderer.gl.getError()===0',quality))
    page.set_viewport_size({'width':1280,'height':800})
    page.click('#reset')
    check('Reset restores controls',page.evaluate('window.__IGNIS__.state.fuel===1 && window.__IGNIS__.state.wind===.12 && window.__IGNIS__.state.mode==="orbit" && window.__IGNIS__.state.quality==="medium"'))
    page.click('#close-settings')
    page.click('#sound')
    page.wait_for_timeout(100)
    check('User action starts audio context',page.evaluate('window.__IGNIS__.audio.enabled && window.__IGNIS__.audio.context.state==="running"'))
    page.click('#sound')
    check('Sound switch stops crackle scheduling',page.evaluate('!window.__IGNIS__.audio.enabled && window.__IGNIS__.audio.timer===null'))
    page.click('#immersive')
    check('Immersive mode hides UI',page.evaluate('document.body.classList.contains("immersive") && !document.getElementById("restore-ui").hidden'))
    page.keyboard.press('Escape')
    check('Escape restores UI',page.evaluate('!document.body.classList.contains("immersive")'))
    # Actual continuous animation uses requestAnimationFrame, not the capture hook.
    page.evaluate('window.__IGNIS__.resume()')
    page.wait_for_timeout(500)
    page.evaluate('window.__IGNIS__.freeze()')
    check('Animation remains live',page.evaluate('window.__IGNIS__.renderer.frame>7'))
    mobile=browser.new_page(viewport={'width':390,'height':844},device_scale_factor=2,is_mobile=True,has_touch=True)
    load(mobile)
    check('Mobile also starts at standard quality',mobile.evaluate('window.__IGNIS__.renderer.quality==="medium"'))
    check('No mobile horizontal overflow',mobile.evaluate('document.documentElement.scrollWidth<=390'))
    mobile.screenshot(path=str(OUT/'mobile.png'),timeout=60000)
    cdp=mobile.context.new_cdp_session(mobile)
    yaw=mobile.evaluate('window.__IGNIS__.cameraGoal.yaw')
    cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':190,'y':410,'id':1}]})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':250,'y':410,'id':1}]})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    check('Mobile one-finger orbit direction',mobile.evaluate('window.__IGNIS__.cameraGoal.yaw')<yaw)
    dist=mobile.evaluate('window.__IGNIS__.cameraGoal.distance')
    cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':140,'y':410,'id':1},{'x':240,'y':410,'id':2}]})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':105,'y':410,'id':1},{'x':275,'y':410,'id':2}]})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]})
    check('Mobile pinch zoom',mobile.evaluate('window.__IGNIS__.cameraGoal.distance')<dist)
    mobile.click('#settings-toggle')
    box=mobile.locator('#settings').bounding_box()
    check('Mobile settings fits viewport',box['x']>=0 and box['x']+box['width']<=390 and box['y']>=0 and box['y']+box['height']<=844)
    mobile.screenshot(path=str(OUT/'mobile-settings.png'))
    mobile.close()
    # Tablet and landscape layout are reflowed from the exact same document.
    for width,height,label in [(820,1180,'tablet'),(844,390,'landscape')]:
        view=browser.new_page(viewport={'width':width,'height':height},device_scale_factor=1)
        load(view)
        check(label+' fits viewport',view.evaluate('(w)=>document.documentElement.scrollWidth<=w',width))
        view.screenshot(path=str(OUT/(label+'.png')),timeout=60000)
        view.close()
    # Reduced-motion preference and no-WebGL are intentional handled states.
    reduced=browser.new_page(viewport={'width':800,'height':600},reduced_motion='reduce')
    load(reduced)
    check('Reduced motion starts paused',reduced.evaluate('window.__IGNIS__.state.paused'))
    reduced.close()
    no_gl=browser.new_page(viewport={'width':600,'height':600})
    no_gl.add_init_script('HTMLCanvasElement.prototype.getContext = function(){return null;}')
    # set_content is used here, so apply the init script directly to the blank document.
    no_gl.evaluate('HTMLCanvasElement.prototype.getContext = function(){return null;}')
    no_gl.set_content(document(),wait_until='load')
    no_gl.wait_for_selector('#error',state='visible')
    check('Unsupported renderer gives a readable error',len(no_gl.inner_text('#error-detail'))>15)
    no_gl.close()
    check('No unexpected browser errors',not report['errors'])
    report['info']=page.evaluate('window.__IGNIS__.info()')
    browser.close()
(OUT/'browser-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
print('COMPLETE',len(report['tests']),'tests',flush=True)
