import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url)));
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const html=read('index.html'),css=read('styles.css');
const context=vm.createContext({console});
for(const f of ['math','shaders','renderer'])vm.runInContext(read(`src/${f}.js`),context);
const I=context.Ignis,M=I.math;
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);

test('Entry document has Japanese language and mobile viewport',()=>{assert.match(html,/<html lang="ja">/);assert.match(html,/viewport-fit=cover/);});
test('Distribution uses separate HTML, CSS, and JavaScript files',()=>{assert.match(html,/href="styles.css"/);assert.match(html,/src="src\/app.js"/);assert.doesNotMatch(html,/<script>\s*\(/);});
test('Every local linked runtime asset exists',()=>{for(const m of html.matchAll(/(?:src|href)="([^"#]+)"/g)){const href=m[1];if(href.startsWith('data:'))continue;assert.ok(fs.existsSync(path.join(root,href)),href);}});
test('No external CDN, remote image, font or module imports',()=>{assert.doesNotMatch(html,/(?:src|href)="https?:/);for(const f of ['math','materials','fuel-world','shaders','renderer','fuel-renderer','audio','app'])assert.doesNotMatch(read(`src/${f}.js`),/\bfetch\s*\(|\bimport\s*\(/);assert.doesNotMatch(css,/@import|https?:\/\//);});
test('Classic deferred script order works without module fetching',()=>{const files=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(m=>m[1]);assert.deepEqual(files,['src/math.js','src/materials.js','src/fuel-world.js','src/shaders.js','src/renderer.js','src/fuel-renderer.js','src/audio.js','src/app.js']);});
test('All JavaScript source files parse',()=>{for(const f of ['math','materials','fuel-world','shaders','renderer','fuel-renderer','audio','app'])assert.doesNotThrow(()=>new vm.Script(read(`src/${f}.js`)));});
test('Clamp bounds both extremes and preserves inner values',()=>{assert.equal(M.clamp(-2,0,1),0);assert.equal(M.clamp(2,0,1),1);assert.equal(M.clamp(.4,0,1),.4);});
test('Interpolation preserves endpoints',()=>{assert.equal(M.mix(2,9,0),2);assert.equal(M.mix(2,9,1),9);assert.equal(M.mix(2,9,.5),5.5);});
test('Normalize makes a unit vector',()=>{close(Math.hypot(...M.normalize([2,3,4])),1);});
test('Normalizing zero does not produce NaN',()=>assert.deepEqual(Array.from(M.normalize([0,0,0])),[0,0,0]));
test('Seeded procedural noise is reproducible',()=>{const a=M.random(42),b=M.random(42);for(let i=0;i<128;i++)assert.equal(a(),b());});
test('Different noise seeds give different values',()=>assert.notEqual(M.random(42)(),M.random(43)()));
test('Random samples stay in the normalized interval',()=>{const r=M.random(1);for(let i=0;i<1000;i++){const v=r();assert.ok(v>=0&&v<1);}});
test('Camera basis is orthonormal',()=>{const c=M.camera(.7,.2,5,[0,1,0]);for(const a of [c.forward,c.right,c.up])close(Math.hypot(...a),1);close(M.dot(c.forward,c.right),0);close(M.dot(c.up,c.right),0);close(M.dot(c.up,c.forward),0);});
test('Camera stays at requested distance',()=>{const c=M.camera(.9,.3,4,[0,1,0]);close(Math.hypot(c.origin[0],c.origin[1]-1,c.origin[2]),4);});
test('Minimum orbit pitch keeps the camera above ground',()=>{for(const y of [0,.8,2,4])assert.ok(M.camera(y,.035,2.9,[0,1.28,0]).origin[1]>0);});
test('The center pixel emits the forward ray',()=>{const c=M.camera(.3,.14,4.9,[0,1.28,0]),r=M.rayAt(640,400,1280,800,c,0,1.95);close(M.dot(c.forward,r),1);});
test('Lens shift positions the fire at the intended screen location',()=>{const c=M.camera(0,0,5,[0,1,0]),shift=.544,x=(1+shift/1.6)*640,r=M.rayAt(x,400,1280,800,c,shift,1.95);close(M.dot(c.forward,r),1);});
test('Ray intersects the interaction plane',()=>{const p=M.intersectPlane([0,1,5],[0,0,-1],[0,1,0],[0,0,1]);assert.deepEqual(Array.from(p),[0,1,0]);});
test('Parallel rays have no plane hit',()=>assert.equal(M.intersectPlane([0,1,5],[1,0,0],[0,1,0],[0,0,1]),null));
test('Plane hits behind the camera are rejected',()=>assert.equal(M.intersectPlane([0,1,5],[0,0,1],[0,1,0],[0,0,1]),null));
test('All atlas dimensions are complete, with no missing slices',()=>{for(const q of Object.values(I.QUALITY)){assert.equal(q.grid[2]%8,0);assert.equal(q.grid[1],q.grid[0]*2);}});
test('Quality levels increase sampling without exceeding shader bounds',()=>{let last=0;for(const name of ['low','medium','high','ultra']){const q=I.QUALITY[name];assert.ok(q.steps>last);assert.ok(q.steps<=180);last=q.steps;}});
test('All shaders use GLSL ES 3.00',()=>{for(const s of Object.values(I.shaders))assert.ok(s.startsWith('#version 300 es'));});
test('Volume and simulation stages use a shared world-space field',()=>{assert.match(I.shaders.simulation,/sampleField/);assert.match(I.shaders.volume,/sampleField/);assert.match(I.shaders.resample,/uNewGrid/);});
test('Accessibility: labels, reduced motion and keyboard affordances',()=>{assert.match(html,/aria-label="描画品質"|for="quality"/);assert.match(css,/prefers-reduced-motion/);assert.match(read('src/app.js'),/ArrowLeft/);assert.match(html,/aria-live="polite"/);});
test('Audio is created only through a user-controlled toggle',()=>{assert.match(read('src/audio.js'),/async toggle/);assert.match(read('src/app.js'),/audio\.toggle\(\)/);assert.doesNotMatch(html,/<audio[^>]+autoplay/);});
