/* IGNIS — interaction, camera, accessible controls, and lifecycle. */
(function(I){'use strict';
const $=id=>document.getElementById(id),M=I.math;
const small=()=>innerWidth<=700;
const defaults=()=>({yaw:.30,pitch:.14,distance:small()?6.25:4.9,target:[0,small()?1.36:1.28,0]});
const params=new URLSearchParams(location.search),capture=params.has('capture');
const state={time:1.7,fuel:1,wind:.12,exposure:1,mode:'orbit',paused:false,immersive:false,quality:'medium',touch:[0,1.1,0,0],shift:0,focal:1.95};
let cameraValues=defaults(),cameraGoal={...cameraValues,target:[...cameraValues.target]},renderer=null,audio=new I.FireAudio(),raf=0,last=0,ready=false,dirty=true,contextLost=false,toastTimer=0;
const pointers=new Map();let lastPinch=0;let totalDrag=0;let pointerStart=null;
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3000);}
function showError(error){console.error(error);$('loading').hidden=true;$('error').hidden=false;$('error-detail').textContent=error?.message||String(error);}
function currentCamera(){return M.camera(cameraValues.yaw,cameraValues.pitch,cameraValues.distance,cameraValues.target);}
function updateCamera(dt){const alpha=1-Math.exp(-Math.max(dt,.008)*12);let change=0;for(const k of ['yaw','pitch','distance']){const before=cameraValues[k];cameraValues[k]=M.mix(before,cameraGoal[k],alpha);change+=Math.abs(cameraValues[k]-before);}state.shift=small()?0:(innerWidth/innerHeight)*.34;return change>.00001;}
function render(dt){const moved=updateCamera(dt);if(!state.paused){state.time+=dt;state.touch[2]*=Math.exp(-dt*1.8);state.touch[3]*=Math.exp(-dt*1.8);}if(!ready)return;renderer.render(state,currentCamera(),state.paused?0:dt);dirty=false;return moved;}
function frame(timestamp){if(contextLost)return;const dt=last?Math.min((timestamp-last)/1000,.05):1/60;last=timestamp;if(!document.hidden&&(!state.paused||dirty||Math.abs(cameraValues.yaw-cameraGoal.yaw)>.0001||Math.abs(cameraValues.pitch-cameraGoal.pitch)>.0001||Math.abs(cameraValues.distance-cameraGoal.distance)>.0001))render(dt);if(!capture)raf=requestAnimationFrame(frame);}
function togglePause(value=!state.paused){state.paused=value;document.body.classList.toggle('paused',value);$('pause').setAttribute('aria-pressed',String(value));$('pause').setAttribute('aria-label',value?'再生':'一時停止');$('pause').title=value?'再生（Space）':'一時停止（Space）';$('pause-icon').innerHTML=value?'<path d="m7 4 9 6-9 6Z"/>':'<path d="M7 4v12M13 4v12"/>';$('live-text').textContent=value?'A MOMENT, HELD STILL':'LIVE GENERATIVE FIRE';audio.setPaused(value||document.hidden);dirty=true;}
function setMode(mode){state.mode=mode;document.body.classList.toggle('wind-mode',mode==='wind');for(const m of ['orbit','wind']){$(`${m}-mode`).classList.toggle('active',m===mode);$(`${m}-mode`).setAttribute('aria-pressed',String(m===mode));}$('gesture-main').textContent=mode==='wind'?'炎の上をなぞって、風を送る':'ドラッグで視点を動かす';$('gesture-sub').textContent=mode==='wind'?'TOUCH THE AIR':small()?'PINCH TO MOVE CLOSER':'SCROLL TO MOVE CLOSER';if(mode==='wind')toast('炎の近くを左右になぞると、気流が変わります。');}
function setImmersive(value){state.immersive=value;document.body.classList.toggle('immersive',value);$('restore-ui').hidden=!value;if(value){setSettings(false);$('restore-ui').focus({preventScroll:true});}else $('immersive').focus({preventScroll:true});}
function setSettings(open){$('settings').hidden=!open;$('settings-toggle').setAttribute('aria-expanded',String(open));if(open)$('close-settings').focus({preventScroll:true});}
function resetCamera(){cameraGoal=defaults();cameraValues.target=[...cameraGoal.target];dirty=true;}
function resetAll(){state.fuel=1;state.wind=.12;state.exposure=1;state.touch=[0,1.1,0,0];for(const k of ['fuel','wind','exposure']){$(k).value=String(state[k]);$(k).dispatchEvent(new Event('input'));}resetCamera();togglePause(false);setMode('orbit');state.quality='medium';$('quality').value='medium';renderer.setQuality('medium');toast('炎と視点を初期状態に戻しました。');}
function touchWind(e,dx,dy){const rect=$('scene').getBoundingClientRect(),cam=currentCamera(),ray=M.rayAt(e.clientX-rect.left,e.clientY-rect.top,rect.width,rect.height,cam,state.shift,state.focal);const p=M.intersectPlane(cam.origin,ray,[0,1.2,0],[cam.forward[0],0,cam.forward[2]]);if(p){state.touch[0]=M.clamp(p[0],-1.2,1.2);state.touch[1]=M.clamp(p[1],.4,3.5);state.touch[2]=M.clamp(state.touch[2]+dx*.043*cam.right[0],-2.1,2.1);state.touch[3]=M.clamp(state.touch[3]+dx*.043*cam.right[2],-2.1,2.1);dirty=true;}}
function pointerMove(e){$('wind-cursor').style.left=`${e.clientX}px`;$('wind-cursor').style.top=`${e.clientY}px`;$('wind-cursor').classList.add('visible');if(!pointers.has(e.pointerId))return;const prev=pointers.get(e.pointerId),dx=e.clientX-prev.x,dy=e.clientY-prev.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});totalDrag+=Math.hypot(dx,dy);if(pointers.size===2){const p=[...pointers.values()],d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);if(lastPinch>0)cameraGoal.distance=M.clamp(cameraGoal.distance*lastPinch/d,small()?4.8:2.9,8.7);lastPinch=d;dirty=true;return;}lastPinch=0;if(state.mode==='wind'&&!e.altKey){touchWind(e,dx,dy);return;}cameraGoal.yaw-=dx*.0045;cameraGoal.pitch=M.clamp(cameraGoal.pitch+dy*.0035,.035,.72);dirty=true;}
function pointerDown(e){if(e.button!==0&&e.button!==2)return;try{$('scene').setPointerCapture(e.pointerId);}catch{}pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});totalDrag=0;pointerStart={x:e.clientX,y:e.clientY};if(pointers.size===2){const p=[...pointers.values()];lastPinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);}else lastPinch=0;}
function pointerUp(e){pointers.delete(e.pointerId);lastPinch=0;if(!pointers.size&&state.mode==='wind'&&totalDrag<8&&pointerStart)touchWind(e,20,0);pointerStart=null;}
function setupUI(){
 $('retry').addEventListener('click',()=>location.reload());$('home').addEventListener('click',e=>{e.preventDefault();resetCamera();});
 $('orbit-mode').addEventListener('click',()=>setMode('orbit'));$('wind-mode').addEventListener('click',()=>setMode('wind'));$('pause').addEventListener('click',()=>togglePause());$('immersive').addEventListener('click',()=>setImmersive(true));$('restore-ui').addEventListener('click',()=>setImmersive(false));
 $('settings-toggle').addEventListener('click',()=>setSettings($('settings').hidden));$('close-settings').addEventListener('click',()=>{setSettings(false);$('settings-toggle').focus({preventScroll:true});});$('reset').addEventListener('click',resetAll);
 for(const key of ['fuel','wind','exposure'])$(key).addEventListener('input',()=>{state[key]=Number($(key).value);audio.fuel=state.fuel;$(key+'-value').textContent=key==='fuel'?(state.fuel<.75?'熾火に近く':state.fuel>1.25?'力強く':'穏やか'):key==='wind'?(state.wind<.05?'無風':state.wind<.30?'かすか':state.wind<.65?'そよぐ':'強く'):state.exposure.toFixed(2);dirty=true;});
 $('quality').addEventListener('change',()=>{const quality=$('quality').value;try{renderer.setQuality(quality);state.quality=quality;dirty=true;}catch(e){showError(e);}});
 $('sound').addEventListener('click',async()=>{try{const enabled=await audio.toggle();audio.setPaused(state.paused||document.hidden);$('sound').setAttribute('aria-pressed',String(enabled));$('sound').setAttribute('aria-label',enabled?'焚き火の音をオフ':'焚き火の音をオン');$('sound').title=enabled?'音をオフ':'音をオン';$('sound-wave').setAttribute('d',enabled?'M13 7c2 1.5 2 4.5 0 6M15 4c4 3 4 9 0 12':'m14 8 4 4m0-4-4 4');}catch(e){toast(e.message||'音声を再生できませんでした。');}});
 const canvas=$('scene');canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('lostpointercapture',e=>{pointers.delete(e.pointerId);lastPinch=0;});canvas.addEventListener('pointerleave',()=>$('wind-cursor').classList.remove('visible'));canvas.addEventListener('contextmenu',e=>e.preventDefault());
 canvas.addEventListener('wheel',e=>{e.preventDefault();cameraGoal.distance=M.clamp(cameraGoal.distance*Math.exp(e.deltaY*.0007),small()?4.8:2.9,8.7);dirty=true;},{passive:false});
 document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();togglePause();}else if(e.key==='Escape'){setSettings(false);if(state.immersive)setImmersive(false);}else if(e.key.toLowerCase()==='h')setImmersive(!state.immersive);else if(e.key.toLowerCase()==='r')resetCamera();else if(e.key==='ArrowLeft'){cameraGoal.yaw+=.09;dirty=true;e.preventDefault();}else if(e.key==='ArrowRight'){cameraGoal.yaw-=.09;dirty=true;e.preventDefault();}else if(e.key==='ArrowUp'){cameraGoal.pitch=M.clamp(cameraGoal.pitch-.05,.035,.72);dirty=true;e.preventDefault();}else if(e.key==='ArrowDown'){cameraGoal.pitch=M.clamp(cameraGoal.pitch+.05,.035,.72);dirty=true;e.preventDefault();}});
 let wasSmall=small();addEventListener('resize',()=>{if(wasSmall!==small()){wasSmall=small();resetCamera();}dirty=true;});
 document.addEventListener('visibilitychange',()=>{last=0;audio.setPaused(state.paused||document.hidden);dirty=true;});
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;cancelAnimationFrame(raf);audio.setPaused(true);toast('描画が中断されました。復元を試みています。');});
 canvas.addEventListener('webglcontextrestored',()=>{try{renderer=new I.Renderer(canvas,{quality:state.quality});contextLost=false;last=0;dirty=true;window.__IGNIS__.renderer=renderer;audio.setPaused(state.paused||document.hidden);raf=requestAnimationFrame(frame);}catch(e){showError(e);}});
 addEventListener('pagehide',()=>{audio.setPaused(true);});
}
async function start(){try{setupUI();await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));renderer=new I.Renderer($('scene'));updateCamera(1);
 // Establish the rising plume before revealing the scene; keep the loader responsive.
 for(let i=0;i<108;i++){state.time+=1/36;const u=renderer.common(state,currentCamera());renderer.simulate(1/36,u);renderer.updateParticles(1/36,state);if(i%18===17)await new Promise(resolve=>requestAnimationFrame(resolve));}
 ready=true;render(1/60);$('loading').classList.add('done');setTimeout(()=>$('loading').hidden=true,1050);$('gesture-sub').textContent=small()?'PINCH TO MOVE CLOSER':'SCROLL TO MOVE CLOSER';
 window.__IGNIS__={state,renderer,audio,get camera(){return currentCamera();},get cameraGoal(){return cameraGoal;},setMode,togglePause,resetCamera,renderStep(dt=1/30){render(dt);},freeze(){cancelAnimationFrame(raf);},resume(){cancelAnimationFrame(raf);last=0;raf=requestAnimationFrame(frame);},info(){return {...renderer.info(),state:{...state},camera:currentCamera()};}};
 if(matchMedia('(prefers-reduced-motion: reduce)').matches){togglePause(true);toast('動きを抑える設定に合わせて、一時停止しています。');}if(!capture)raf=requestAnimationFrame(frame);
}catch(e){showError(e);}}
start();
})(globalThis.Ignis=globalThis.Ignis||{});
